[package]

name = "colors"
version = "0.1.0"
authors = ["Arturo Castro", "Brendan Zabarauskas <bjzaba@yahoo.com.au>", "Luqman Aden"]
description = "A library that provides types and conversions for working with various color formats. Forked from the unmuntained crate color"
license=LICENSE
repository=https://github.com/arturoc/colors-rs

[dependencies]
num-traits = "0.2"
angle = "0.3"
